// Department Action Types
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_LOADING = "FETCH_DEPARTMENT_LOADING";
export const FETCH_DEPARTMENT_ERROR = "FETCH_DEPARTMENT_ERROR";

// Category Action Types
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';

// Shopping Cart Action Types
export const FETCH_CART_PRODUCT_SUCCESS = 'FETCH_CART_PRODUCT_SUCCESS';
export const FETCH_CART_PRODUCT_LOADING = 'FETCH_CART_PRODUCT_LOADING';
export const FETCH_CART_PRODUCT_ERROR = 'FETCH_CART_PRODUCT_ERROR';
