// Department Action Types
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_LOADING = "FETCH_DEPARTMENT_LOADING";
export const FETCH_DEPARTMENT_ERROR = "FETCH_DEPARTMENT_ERROR";

// Category Action Types
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';

// Shopping Cart Action Types
export const FETCH_CART_PRODUCT_SUCCESS = 'FETCH_CART_PRODUCT_SUCCESS';
export const FETCH_CART_PRODUCT_LOADING = 'FETCH_CART_PRODUCT_LOADING';
export const FETCH_CART_PRODUCT_ERROR = 'FETCH_CART_PRODUCT_ERROR';

// Product Action Types
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_ONE_PRODUCT_SUCCESS = 'FETCH_ONE_PRODUCT_SUCCESS';
export const FETCH_ONE_PRODUCT_LOADING = 'FETCH_ONE_PRODUCT_LOADING';
export const FETCH_ONE_PRODUCT_ERROR = 'FETCH_ONE_PRODUCT_ERROR';


//Attributes Action Types
export const FETCH_PRODUCT_ATTRIBUTE_SUCCESS = 'FETCH_PRODUCT_ATTRIBUTE_SUCCESS';
export const FETCH_PRODUCT_ATTRIBUTE_LOADING = 'FETCH_PRODUCT_ATTRIBUTE_LOADING';
export const FETCH_PRODUCT_ATTRIBUTE_ERROR = 'FETCH_PRODUCT_ATTRIBUTE_ERROR';
