// Department Action Types
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_LOADING = "FETCH_DEPARTMENT_LOADING";
export const FETCH_DEPARTMENT_ERROR = "FETCH_DEPARTMENT_ERROR";
export const FETCH_ONE_DEPARTMENT_SUCCESS = "FETCH_ONE_DEPARTMENT_SUCCESS";
export const FETCH_ONE_DEPARTMENT_LOADING = "FETCH_ONE_DEPARTMENT_LOADING";
export const FETCH_ONE_DEPARTMENT_ERROR = "FETCH_ONE_DEPARTMENT_ERROR";

// Category Action Types
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';
export const FETCH_ONE_CATEGORY_SUCCESS = 'FETCH_ONE_CATEGORY_SUCCESS';
export const FETCH_ONE_CATEGORY_LOADING = 'FETCH_ONE_CATEGORY_LOADING';
export const FETCH_ONE_CATEGORY_ERROR = 'FETCH_ONE_CATEGORY_ERROR';

// Shopping Cart Action Types
export const FETCH_CART_PRODUCT_SUCCESS = 'FETCH_CART_PRODUCT_SUCCESS';
export const FETCH_CART_PRODUCT_LOADING = 'FETCH_CART_PRODUCT_LOADING';
export const FETCH_CART_PRODUCT_ERROR = 'FETCH_CART_PRODUCT_ERROR';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const UPDATE_CART_QUANTITY_SUCCESS = 'UPDATE_CART_QUANTITY_SUCCESS';
export const UPDATE_CART_QUANTITY_LOADING = 'UPDATE_CART_QUANTITY_LOADING';
export const UPDATE_CART_QUANTITY_ERROR = 'UPDATE_CART_QUANTITY_ERROR';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS'
export const DELETE_CART_ITEM_LOADING = 'DELETE_CART_ITEM_LOADING'
export const DELETE_CART_ITEM_ERROR = 'DELETE_CART_ITEM_ERROR'
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_LOADING = 'EMPTY_CART_LOADING';
export const EMPTY_CART_ERROR = 'EMPTY_CART_ERROR';
export const UPDATE_CUSTOMER_ADDRESS = 'UPDATE_CUSTOMER_ADDRESS';
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = 'UPDATE_CUSTOMER_ADDRESS_SUCCESS';
export const UPDATE_CUSTOMER_ADDRESS_ERROR = 'UPDATE_CUSTOMER_ADDRESS_ERROR';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const PAY_WITH_STRIPE = 'PAY_WITH_STRIPE';
export const PAY_WITH_STRIPE_SUCCESS = 'PAY_WITH_STRIPE_SUCCESS';
export const PAY_WITH_STRIPE_ERROR = 'PAY_WITH_STRIPE_ERROR';


// Product Action Types
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_ONE_PRODUCT_SUCCESS = 'FETCH_ONE_PRODUCT_SUCCESS';
export const FETCH_ONE_PRODUCT_LOADING = 'FETCH_ONE_PRODUCT_LOADING';
export const FETCH_ONE_PRODUCT_ERROR = 'FETCH_ONE_PRODUCT_ERROR';
export const CATEGORY_PRODUCTS = 'CATEGORY_PRODUCTS';
export const CATEGORY_PRODUCTS_SUCCESS = 'CATEGORY_PRODUCTS_SUCCESS';
export const CATEGORY_PRODUCTS_ERROR = 'CATEGORY_PRODUCTS_ERROR';
export const DEPARTMENT_PRODUCTS = 'DEPARTMENT_PRODUCTS';
export const DEPARTMENT_PRODUCTS_SUCCESS = 'DEPARTMENT_PRODUCTS_SUCCESS';
export const DEPARTMENT_PRODUCTS_ERROR = 'DEPARTMENT_PRODUCTS_ERROR';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR';

//Attributes Action Types
export const FETCH_PRODUCT_ATTRIBUTE_SUCCESS = 'FETCH_PRODUCT_ATTRIBUTE_SUCCESS';
export const FETCH_PRODUCT_ATTRIBUTE_LOADING = 'FETCH_PRODUCT_ATTRIBUTE_LOADING';
export const FETCH_PRODUCT_ATTRIBUTE_ERROR = 'FETCH_PRODUCT_ATTRIBUTE_ERROR';


// AUTH Action Types
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
